name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - conda=25.7.0
  - setuptools
  - pip
  - wheel
  - conda-anaconda-telemetry
  - conda-anaconda-tos[version='>=0.1.3']
  - conda-content-trust
  - conda-libmamba-solver
  - menuinst
  - python.app
  - anaconda-anon-usage
prefix: /Users/kmarvel/miniconda3
